/* Cub Quest — shared mini-game shell. Touch-first, audio-first, offline-friendly. */
(function(){
  "use strict";
  if(window.CubQuestGames) return;

  var W=800,H=520,registry={},current=null,raf=0,last=0,paused=false;
  var HONEY="#FFC24F",MOON="#F7F2E4",SOFT="#1A2942",LINE="#2C4064";

  var style=document.createElement("style");
  style.textContent=`
    #cqGameShell{position:fixed;inset:0;z-index:160;display:none;flex-direction:column;background:#0a1220;color:${MOON};font-family:"Nunito",system-ui,sans-serif;touch-action:none;overscroll-behavior:none}
    #cqGameShell.on{display:flex}.cqg-head{display:flex;align-items:center;gap:12px;width:min(100% - 24px,860px);margin:0 auto;padding:calc(10px + env(safe-area-inset-top)) 0 8px}.cqg-title{min-width:0;flex:1}.cqg-title h2{margin:0;font-family:"Grandstander","Nunito",sans-serif;color:${HONEY};font-size:clamp(1.35rem,5vw,2rem);line-height:1}.cqg-title p{margin:3px 0 0;color:#c8d0de;font-size:.82rem;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cqg-close{width:50px;height:50px;flex:none;border-radius:50%;background:${SOFT};border:2px solid ${LINE};font-size:1.5rem;font-weight:900;color:${MOON}}
    .cqg-hud{display:flex;align-items:center;gap:10px;width:min(100% - 24px,840px);margin:0 auto 8px}.cqg-score{padding:8px 14px;border:2px solid ${LINE};border-radius:999px;background:${SOFT};color:${HONEY};font-family:"Grandstander",sans-serif;font-weight:850}.cqg-hint{margin-left:auto;color:#bfc8da;font-size:.8rem;font-weight:750;text-align:right}.cqg-pulse{display:none;border:0;border-radius:999px;background:${HONEY};color:#241704;font-family:"Grandstander",sans-serif;font-weight:900;padding:10px 16px}.cqg-pulse.on{display:inline-flex}
    .cqg-stage{position:relative;flex:1;min-height:280px;width:min(100%,880px);margin:0 auto;overflow:hidden}.cqg-stage canvas{display:block;width:100%;height:100%;touch-action:none}.cqg-fact{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%) scale(.92);width:min(88%,520px);padding:22px 20px;background:rgba(10,18,32,.97);border:3px solid ${HONEY};border-radius:28px;text-align:center;box-shadow:0 22px 60px rgba(0,0,0,.5);opacity:0;pointer-events:none;transition:.2s ease}.cqg-fact.on{opacity:1;transform:translate(-50%,-50%) scale(1);pointer-events:auto}.cqg-fact b{display:block;color:${HONEY};font-family:"Grandstander",sans-serif;font-size:1.45rem;margin-bottom:7px}.cqg-fact p{margin:0 0 16px;font-size:1.05rem;line-height:1.42}.cqg-fact button{border:0;border-radius:999px;background:${HONEY};color:#241704;font-family:"Grandstander",sans-serif;font-weight:900;padding:12px 20px;font-size:1rem}@media(max-width:520px){.cqg-hint{font-size:.7rem}.cqg-stage{min-height:250px}.cqg-head,.cqg-hud{width:calc(100% - 18px)}}
  `;
  document.head.appendChild(style);

  var shell=document.createElement("section");
  shell.id="cqGameShell";shell.setAttribute("role","dialog");shell.setAttribute("aria-modal","true");
  shell.innerHTML=`<div class="cqg-head"><div class="cqg-title"><h2 id="cqgTitle"></h2><p id="cqgGoal"></p></div><button class="cqg-close" id="cqgClose" aria-label="Close game">×</button></div><div class="cqg-hud"><span class="cqg-score" id="cqgScore"></span><button class="cqg-pulse" id="cqgPulse">📡 Echo!</button><span class="cqg-hint" id="cqgHint"></span></div><div class="cqg-stage" id="cqgStage"><canvas id="cqgCanvas"></canvas><div class="cqg-fact" id="cqgFact"><b id="cqgFactTitle"></b><p id="cqgFactText"></p><button id="cqgNext">Keep going</button></div></div>`;
  document.body.appendChild(shell);

  var canvas=document.getElementById("cqgCanvas"),ctx=canvas.getContext("2d"),stage=document.getElementById("cqgStage");
  var titleEl=document.getElementById("cqgTitle"),goalEl=document.getElementById("cqgGoal"),scoreEl=document.getElementById("cqgScore"),hintEl=document.getElementById("cqgHint"),pulseEl=document.getElementById("cqgPulse");
  var factEl=document.getElementById("cqgFact"),factTitle=document.getElementById("cqgFactTitle"),factText=document.getElementById("cqgFactText"),nextEl=document.getElementById("cqgNext");

  function canSpeak(){return "speechSynthesis" in window&&typeof window.SpeechSynthesisUtterance==="function";}
  function stopSpeaking(){if(canSpeak())try{window.speechSynthesis.cancel();}catch(e){}if(window.stopSpeaking)try{window.stopSpeaking();}catch(e){}}
  function speak(text){if(!text||!canSpeak())return;try{window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang="en-IE";u.rate=.9;u.pitch=1.06;window.speechSynthesis.speak(u);}catch(e){}}
  function chime(){if(window.chime)try{window.chime();}catch(e){}}
  function rand(a,b){return a+Math.random()*(b-a)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function d2(a,b){var x=a.x-b.x,y=a.y-b.y;return x*x+y*y}
  function resize(){if(!current)return;var r=stage.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);}
  window.addEventListener("resize",function(){if(current)resize();});
  function emoji(text,x,y,size,alpha){ctx.save();ctx.globalAlpha=alpha==null?1:alpha;ctx.font=size+"px Apple Color Emoji,Segoe UI Emoji,sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,x,y);ctx.restore();}
  function circle(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}

  function safePoint(s){var x,y,tries=0;do{x=rand(70,W-70);y=rand(70,H-65);tries++;}while(tries<80&&s.obstacles.some(function(o){return (x-o.x)*(x-o.x)+(y-o.y)*(y-o.y)<(o.r+55)*(o.r+55)}));return{x:x,y:y};}
  function makeState(c){var s={c:c,score:0,target:c.target||10,player:{x:c.mode==="runner"?165:90,y:H/2,vx:0,vy:0,r:26},pointer:null,keys:{},targets:[],obstacles:[],platforms:[],scroll:0,revealUntil:0,milestones:{},complete:false},i,p,obs=c.obstacleEmoji||["🪨","🌿","🪵"];for(i=0;i<(c.obstacles||0);i++){s.obstacles.push({x:rand(180,W-70),y:rand(70,H-60),r:rand(30,48),emoji:obs[i%obs.length]});}if(c.mode==="jump"){for(i=0;i<s.target+2;i++)s.platforms.push({x:75+i*(W-150)/(s.target+1),y:90+((i*83)%320),r:31,hit:i===0});s.player.x=s.platforms[0].x;s.player.y=s.platforms[0].y;}else{for(i=0;i<s.target;i++){p=safePoint(s);s.targets.push({x:p.x,y:p.y,r:16,alive:true,phase:i*.7,hidden:!!c.hideTargets});}}return s;}
  function updateScore(s){scoreEl.textContent=(s.c.scoreLabel||"Found")+" "+s.score+" / "+s.target;}
  function showFact(s,f,done){paused=true;factTitle.textContent=f.title||"Great job!";factText.textContent=f.text||"";nextEl.textContent=done?"Play again":"Keep going";factEl.classList.add("on");speak((f.title||"")+" "+(f.text||""));}
  function maybeFact(s){var fs=s.c.facts||[];for(var i=0;i<fs.length;i++){var f=fs[i],at=f.at||Math.round((i+1)*s.target/fs.length);if(s.score>=at&&!s.milestones[i]){s.milestones[i]=true;showFact(s,f,s.score>=s.target);break;}}}
  function collectTarget(s,t){if(!t.alive)return;t.alive=false;s.score++;chime();updateScore(s);maybeFact(s);if(s.score>=s.target)s.complete=true;}
  function obstacleBounce(s){s.obstacles.forEach(function(o){var dx=s.player.x-o.x,dy=s.player.y-o.y,d=Math.sqrt(dx*dx+dy*dy)||1,min=s.player.r+o.r;if(d<min){s.player.x=o.x+dx/d*min;s.player.y=o.y+dy/d*min;s.player.vx*=-.25;s.player.vy*=-.25;}});}
  function steer(s,dt){var ax=0,ay=0,acc=980;if(s.keys.ArrowLeft||s.keys.a)ax--;if(s.keys.ArrowRight||s.keys.d)ax++;if(s.keys.ArrowUp||s.keys.w)ay--;if(s.keys.ArrowDown||s.keys.s)ay++;if(s.pointer){var dx=s.pointer.x-s.player.x,dy=s.pointer.y-s.player.y,d=Math.sqrt(dx*dx+dy*dy);if(d>8){ax+=dx/d;ay+=dy/d}else s.pointer=null;}var m=Math.sqrt(ax*ax+ay*ay);if(m>1){ax/=m;ay/=m;}s.player.vx=(s.player.vx+ax*acc*dt)*Math.pow(.055,dt);s.player.vy=(s.player.vy+ay*acc*dt)*Math.pow(.055,dt);var sp=Math.sqrt(s.player.vx*s.player.vx+s.player.vy*s.player.vy),mx=s.c.speed||235;if(sp>mx){s.player.vx=s.player.vx/sp*mx;s.player.vy=s.player.vy/sp*mx;}s.player.x=clamp(s.player.x+s.player.vx*dt,s.player.r,W-s.player.r);s.player.y=clamp(s.player.y+s.player.vy*dt,s.player.r,H-s.player.r);obstacleBounce(s);}
  function update(s,dt,t){if(s.c.mode==="runner"){var dy=0;if(s.keys.ArrowUp||s.keys.w)dy=-1;if(s.keys.ArrowDown||s.keys.s)dy=1;if(s.pointer)dy=clamp((s.pointer.y-s.player.y)/90,-1,1);s.player.vy=(s.player.vy+dy*760*dt)*Math.pow(.08,dt);s.player.y=clamp(s.player.y+s.player.vy*dt,45,H-45);s.scroll+=(s.c.scrollSpeed||155)*dt;s.targets.forEach(function(o,i){if(!o.alive)return;var x=((o.x-s.scroll+i*240)%(W+260)+W+260)%(W+260)-80;if((x-s.player.x)*(x-s.player.x)+(o.y-s.player.y)*(o.y-s.player.y)<52*52)collectTarget(s,o);});}else if(s.c.mode==="jump"){var dest=s.pointer;if(dest){var best=-1,bd=1e9;s.platforms.forEach(function(p,i){if(p.hit)return;var dd=(p.x-dest.x)*(p.x-dest.x)+(p.y-dest.y)*(p.y-dest.y);if(dd<bd){bd=dd;best=i;}});if(best>=0&&bd<90*90){var p=s.platforms[best];p.hit=true;s.player.x=p.x;s.player.y=p.y;s.pointer=null;s.score++;updateScore(s);chime();maybeFact(s);if(s.score>=s.target)s.complete=true;}}}else{steer(s,dt);s.targets.forEach(function(o){if(!o.alive)return;var visible=!o.hidden||t<s.revealUntil||d2(s.player,o)<80*80;if(visible&&d2(s.player,o)<(s.player.r+o.r+6)*(s.player.r+o.r+6))collectTarget(s,o);});}}
  function drawBackdrop(s){var c=s.c,g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,(c.colors&&c.colors[0])||"#123047");g.addColorStop(1,(c.colors&&c.colors[1])||"#19372d");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(var i=0;i<35;i++)circle((i*113)%W,(i*67)%H,1+(i%3)*.45,"rgba(247,242,228,.13)");}
  function draw(s,t){ctx.clearRect(0,0,W,H);drawBackdrop(s);if(s.c.mode==="jump"){s.platforms.forEach(function(p){emoji(s.c.platformEmoji||"🍃",p.x,p.y,44,p.hit ? .4 : 1);});}else{s.obstacles.forEach(function(o){emoji(o.emoji,o.x,o.y,54,.95);});s.targets.forEach(function(o,i){if(!o.alive)return;var x=o.x;if(s.c.mode==="runner")x=((o.x-s.scroll+i*240)%(W+260)+W+260)%(W+260)-80;var visible=!o.hidden||t<s.revealUntil||d2(s.player,o)<80*80;emoji(visible?(s.c.targetEmoji||"⭐"):(s.c.hiddenEmoji||"🌾"),x,o.y,34,visible?1:.9);});}emoji(s.c.playerEmoji||"🐾",s.player.x,s.player.y,54,1);if(s.c.mode==="search"&&t<s.revealUntil){ctx.strokeStyle="rgba(111,168,220,.55)";ctx.lineWidth=4;ctx.beginPath();ctx.arc(s.player.x,s.player.y,95+(t%450)/4,0,Math.PI*2);ctx.stroke();}}
  function loop(t){if(!current||paused)return;var dt=Math.min(.033,(t-last)/1000||.016);last=t;update(current,dt,t);draw(current,t);raf=requestAnimationFrame(loop);}
  function pointer(e){var r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
  canvas.addEventListener("pointerdown",function(e){if(!current||paused)return;current.pointer=pointer(e);canvas.setPointerCapture&&canvas.setPointerCapture(e.pointerId);});canvas.addEventListener("pointermove",function(e){if(!current||paused)return;if(e.buttons||e.pointerType==="touch")current.pointer=pointer(e);});window.addEventListener("keydown",function(e){if(!current)return;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","a","d","w","s"].indexOf(e.key)>=0){current.keys[e.key]=true;e.preventDefault();}});window.addEventListener("keyup",function(e){if(current)current.keys[e.key]=false;});
  pulseEl.addEventListener("click",function(){if(!current||paused)return;current.revealUntil=performance.now()+1600;speak(current.c.pulseNarration||"Ping! Listen for the echo.");});
  nextEl.addEventListener("click",function(){stopSpeaking();factEl.classList.remove("on");if(current&&current.complete){start(current.c.id);return;}paused=false;last=performance.now();raf=requestAnimationFrame(loop);});
  function stop(){if(raf)cancelAnimationFrame(raf);raf=0;paused=false;stopSpeaking();factEl.classList.remove("on");shell.classList.remove("on");current=null;}
  function start(id){var c=registry[id];if(!c)return false;stop();current=makeState(c);titleEl.textContent=c.title;goalEl.textContent=c.goal;hintEl.textContent=c.hint||"Tap or drag to move";pulseEl.classList.toggle("on",c.mode==="search");shell.classList.add("on");paused=false;updateScore(current);resize();draw(current,performance.now());last=performance.now();raf=requestAnimationFrame(loop);setTimeout(function(){speak(c.openNarration||c.goal);},160);return true;}
  document.getElementById("cqgClose").addEventListener("click",stop);
  function register(c){if(!c||!c.id||!c.title)throw new Error("Invalid Cub Quest game config");registry[c.id]=c;return c;}function list(){return Object.keys(registry).map(function(k){return registry[k];});}
  window.CubQuestGames={register:register,open:start,close:stop,list:list,speak:speak,stopSpeaking:stopSpeaking};
  window.dispatchEvent(new Event("cubquest-games-ready"));
})();
