/* Cub Quest — water and seashore mini-game registrations. */
(function(){
  "use strict";
  function ready(fn){if(window.CubQuestGames)fn();else window.addEventListener("cubquest-games-ready",fn,{once:true});}
  ready(function(){var G=window.CubQuestGames;
    G.register({id:"otter",title:"River Slide",goal:"Swim through the river and collect 9 fish!",openNarration:"River Slide! Drag up and down to help the otter swim through the river and collect nine fish.",mode:"runner",target:9,scoreLabel:"Fish",playerEmoji:"🦦",targetEmoji:"🐟",obstacles:0,colors:["#12354a","#1c5964"],hint:"Drag up and down",scrollSpeed:150,facts:[{at:3,title:"Warm fur!",text:"Otters have thick fur that helps keep them warm."},{at:6,title:"Whisker sensors!",text:"Their whiskers can sense movement in the water."},{at:9,title:"Home sweet holt!",text:"An otter's home can be called a holt."}]});

    G.register({id:"grey-seal",title:"Seal Splash",goal:"Dive through the kelp and collect 9 fish!",openNarration:"Seal Splash! Drag up and down to help the grey seal dive through the kelp and collect nine fish.",mode:"runner",target:9,scoreLabel:"Fish",playerEmoji:"🦭",targetEmoji:"🐟",obstacles:0,colors:["#0d3850","#176078"],hint:"Drag up and down",scrollSpeed:145,facts:[{at:3,title:"Whisker tracker!",text:"A seal's whiskers can track movement in the water."},{at:6,title:"Super-rich milk!",text:"Grey seal pups drink extremely rich milk."},{at:9,title:"Give pups space!",text:"If you see a seal pup resting on shore, give it lots of space."}]});

    G.register({id:"puffin",title:"Puffin Fishing",goal:"Catch 8 fish and bring a beakful home!",openNarration:"Puffin Fishing! Guide the puffin through the water and catch eight little fish for the puffling.",mode:"runner",target:8,scoreLabel:"Fish",playerEmoji:"🐧",targetEmoji:"🐟",obstacles:0,colors:["#17425c","#276f7d"],hint:"Drag up and down",scrollSpeed:155,facts:[{at:3,title:"Fishy beak!",text:"Puffins can hold several fish across their beak at once."},{at:6,title:"Puffling!",text:"A baby puffin is called a puffling."},{at:8,title:"Burrow home!",text:"Puffins nest in burrows near the sea."}]});

    G.register({id:"dolphin",title:"Echo Explorer",goal:"Use echo pulses to find 9 hidden fish!",openNarration:"Echo Explorer! Tap Echo to reveal hidden fish, then swim to them and find nine.",mode:"search",target:9,scoreLabel:"Fish",playerEmoji:"🐬",targetEmoji:"🐟",hiddenEmoji:"◌",hideTargets:true,obstacles:3,obstacleEmoji:["🪨","🌿","🪸"],colors:["#0d4160","#176b85"],hint:"Tap Echo, then drag to a fish",pulseNarration:"Click click! The echoes show where the fish are.",facts:[{at:3,title:"Echo clicks!",text:"Dolphins use clicks and echoes to explore underwater."},{at:6,title:"Special whistle!",text:"Each dolphin can have its own signature whistle."},{at:9,title:"Family team!",text:"Bottlenose dolphins often live in social family groups."}]});

    G.register({id:"basking-shark",title:"Plankton Parade",goal:"Swim through 10 clouds of tiny plankton!",openNarration:"Plankton Parade! Guide the basking shark through ten clouds of tiny plankton.",mode:"collect",target:10,scoreLabel:"Clouds",playerEmoji:"🦈",targetEmoji:"✨",obstacles:5,obstacleEmoji:["🪨","🌿","🫧"],colors:["#0e4055","#17697a"],hint:"Tap or drag to the plankton",speed:205,facts:[{at:3,title:"Filter feeder!",text:"Basking sharks filter tiny plankton from the water."},{at:7,title:"Gentle giant!",text:"Those huge sharks are harmless to people."},{at:10,title:"Enormous shark!",text:"Basking sharks can grow to enormous sizes."}]});
  });
})();
