/* Cub Quest — woodland mini-game registrations. */
(function(){
  "use strict";
  function ready(fn){if(window.CubQuestGames)fn();else window.addEventListener("cubquest-games-ready",fn,{once:true});}
  ready(function(){var G=window.CubQuestGames;
    G.register({id:"fox",title:"Fox Pounce",goal:"Find 9 rustling food spots in the grass!",openNarration:"Fox Pounce! Move through the grass. Follow the rustles and find nine hidden food spots.",mode:"collect",target:9,scoreLabel:"Found",playerEmoji:"🦊",targetEmoji:"🐭",hiddenEmoji:"🌾",hideTargets:true,obstacles:5,obstacleEmoji:["🌳","🪨","🌿"],colors:["#20324a","#29462f"],hint:"Tap or drag through the grass",facts:[{at:3,title:"Super ears!",text:"Foxes can hear tiny animals moving under grass."},{at:6,title:"Fluffy brush!",text:"A fox's big fluffy tail is called a brush."},{at:9,title:"Clever explorer!",text:"Foxes can live in woods, fields and even towns."}]});

    G.register({id:"hedgehog",title:"Leafy Hideaway",goal:"Collect 9 cosy leaves for the hedgehog's nest!",openNarration:"Leafy Hideaway! Help the hedgehog collect nine cosy leaves for its nest.",mode:"collect",target:9,scoreLabel:"Leaves",playerEmoji:"🦔",targetEmoji:"🍂",obstacles:4,obstacleEmoji:["🪨","🌳","🌼"],colors:["#213448","#31472d"],hint:"Tap or drag to the leaves",facts:[{at:3,title:"Cosy nest!",text:"Hedgehogs make cosy nests from leaves and grass."},{at:6,title:"Spiky shield!",text:"A hedgehog's spines help protect it."},{at:9,title:"Hedgehog highway!",text:"A small gap under a garden fence can help hedgehogs travel safely."}]});

    G.register({id:"pine-marten",title:"Treetop Trail",goal:"Jump across 8 branches and reach the far tree!",openNarration:"Treetop Trail! Tap the next branch to help the pine marten climb across the trees.",mode:"jump",target:8,scoreLabel:"Branches",playerEmoji:"🐾",platformEmoji:"🌿",colors:["#173248","#24452f"],hint:"Tap a nearby branch",facts:[{at:3,title:"Tree climber!",text:"Pine martens are brilliant tree climbers."},{at:6,title:"Twisty ankles!",text:"They can turn their ankles to climb down trees head first."},{at:8,title:"Special bib!",text:"The pale patch on a pine marten's chest is called a bib."}]});

    G.register({id:"stoat",title:"Stone Wall Sprint",goal:"Find 9 scent markers through the stone wall!",openNarration:"Stone Wall Sprint! Help the stoat slip through the wall and find nine scent markers.",mode:"collect",target:9,scoreLabel:"Scents",playerEmoji:"🐾",targetEmoji:"✨",obstacles:7,obstacleEmoji:["🪨","🧱","🌿"],colors:["#283343","#374235"],hint:"Tap or drag through the gaps",facts:[{at:3,title:"Squeeze through!",text:"A stoat's long thin body helps it slip through small gaps."},{at:6,title:"Black tail tip!",text:"Look for the black tip on a stoat's tail."},{at:9,title:"Irish stoat!",text:"Ireland has stoats, but no native weasels."}]});

    G.register({id:"frog",title:"Lily Pad Leap",goal:"Leap across 8 lily pads and catch the flies!",openNarration:"Lily Pad Leap! Tap the lily pads to help the frog bounce across the pond.",mode:"jump",target:8,scoreLabel:"Jumps",playerEmoji:"🐸",platformEmoji:"🪷",colors:["#153c55","#1d5d61"],hint:"Tap the next lily pad",facts:[{at:3,title:"Big jump!",text:"Frogs use powerful back legs to jump."},{at:6,title:"Growing up!",text:"Frogspawn grows into tadpoles, then froglets."},{at:8,title:"Winter snooze!",text:"Some frogs spend winter tucked into mud at the bottom of ponds."}]});
  });
})();
