/* Cub Quest — temporary all-access mode for quizzes and games. */
(function(){
  "use strict";
  var ALWAYS_AVAILABLE=true;
  if(!ALWAYS_AVAILABLE)return;

  var BANK={
    "Badgers":[["What do badgers love to eat?",["Worms","Bananas","Fish"],0],["Where does a badger sleep?",["In a sett","In a nest","In the sea"],0],["When are badgers usually awake?",["At night","At lunchtime","Only in winter"],0]],
    "Foxes":[["What is a fox called in Irish?",["Madra rua","Loscán","Rón mór"],0],["What is a fox's bushy tail called?",["A brush","A paddle","A fan"],0],["What can a fox hear in long grass?",["A tiny mouse","A whale","A shark"],0]],
    "Bats":[["What are bats the only furry animals able to do?",["Really fly","Breathe underwater","Change colour"],0],["What does a bat use to find things in the dark?",["Echolocation","A torch","Its whiskers"],0],["What is a baby bat called?",["A pup","A calf","A hoglet"],0]],
    "Hedgehogs":[["What covers a hedgehog's back?",["Spines","Feathers","Scales"],0],["What does a hedgehog do when frightened?",["Rolls into a ball","Flies away","Jumps into water"],0],["What is a baby hedgehog called?",["A hoglet","A puffling","A kit"],0]],
    "Barn Owls":[["How does a barn owl fly?",["Very quietly","Very noisily","Only underwater"],0],["What shape is a barn owl's face?",["A heart","A square","A triangle"],0],["What does a barn owl cough up after eating?",["A pellet","A shell","A cocoon"],0]],
    "Otters":[["Where does an otter live?",["In a holt","In a sett","In a cocoon"],0],["What do otters love to eat?",["Fish","Grass","Acorns"],0],["What helps an otter feel fish moving in muddy water?",["Whiskers","Horns","Feathers"],0]],
    "Pine Martens":[["Where is a pine marten happiest?",["Climbing in woods","Swimming in the sea","Living on open sand"],0],["What is the creamy patch on its chest called?",["A bib","A hood","A mask"],0],["What are baby pine martens called?",["Kits","Calves","Owlets"],0]],
    "Stoats":[["What colour is the tip of a stoat's tail?",["Black","Blue","Orange"],0],["What shape is a stoat's body?",["Long and thin","Round and flat","Short and spiky"],0],["What are baby stoats called?",["Kits","Pups","Pufflings"],0]],
    "Frogs":[["What do frog eggs in a pond form?",["Frogspawn","A cocoon","A pellet"],0],["What does a tadpole grow first?",["Back legs","Wings","Feathers"],0],["What can a frog breathe through?",["Its skin","Its shell","Its fur"],0]],
    "Moths":[["What does a moth start life as?",["An egg","A fish","A pup"],0],["What does a moth use to drink nectar?",["A long curled tongue","A beak","Whiskers"],0],["What do many moths help flowers with?",["Pollination","Digging","Swimming"],0]],
    "Grey Seals":[["What is a baby seal called?",["A pup","A kit","A hoglet"],0],["What do seals mainly eat?",["Fish","Leaves","Berries"],0],["What helps a seal detect movement in water?",["Whiskers","Antlers","Wings"],0]],
    "Puffins":[["What is a baby puffin called?",["A puffling","A calf","A hoglet"],0],["Where does a puffin nest?",["In a burrow","In a tall tree","Underwater"],0],["What can a puffin carry lots of in its beak?",["Fish","Apples","Stones"],0]],
    "Dolphins":[["How does a dolphin breathe?",["Through a blowhole","Through gills","Through its skin"],0],["What is a baby dolphin called?",["A calf","A kit","A pup"],0],["How does a dolphin find fish in dark water?",["Echolocation","A lantern","Smell alone"],0]],
    "Basking Sharks":[["What does a basking shark eat?",["Plankton","Seals","People"],0],["How big can a basking shark grow?",["About as long as a bus","About as long as a pencil","About as long as a shoe"],0],["Is a basking shark dangerous to people?",["No, it is harmless","Yes, it hunts people","Only on land"],0]]
  };

  function speak(text){
    if(!("speechSynthesis" in window))return;
    try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang="en-IE";u.rate=.9;u.pitch=1.04;speechSynthesis.speak(u);}catch(e){}
  }
  function animalName(){var n=document.getElementById("lessonName");return n?n.textContent.trim():"";}
  function ensureStyle(){if(document.getElementById("cqAllAccessStyle"))return;var s=document.createElement("style");s.id="cqAllAccessStyle";s.textContent=".cq-all-quiz{--tint:#FFC24F!important;border-color:#8b6b14!important;background:linear-gradient(145deg,#4b3b14,#66501a)!important;min-height:150px}.cq-all-quiz .cq-q-art{width:84px;height:84px;display:grid;place-items:center;border-radius:24px;background:#FFC24F;color:#241704;font-size:3rem}.cq-all-quiz .cq-q-meta b{color:#fff!important}.cq-all-quiz .cq-q-meta small{display:block;margin-top:5px;color:#F7F2E4;font-weight:800}.cq-quiz-overlay{position:fixed;inset:0;z-index:20000;background:#101B2E;display:flex;align-items:center;justify-content:center;padding:22px}.cq-quiz-box{width:min(560px,100%);background:#17263d;border:3px solid #FFC24F;border-radius:28px;padding:24px;color:#fff;text-align:center}.cq-quiz-box h2{margin:0 0 10px;font-size:1.8rem}.cq-quiz-box p{font-size:1.35rem;font-weight:900}.cq-quiz-choices{display:grid;gap:12px;margin-top:20px}.cq-quiz-choice{font:inherit;font-weight:900;font-size:1.1rem;padding:16px;border:0;border-radius:18px;background:#F7F2E4;color:#101B2E}.cq-quiz-close{margin-top:18px;background:transparent;color:#fff;border:2px solid #fff;border-radius:16px;padding:10px 18px;font-weight:900}.cq-quiz-good{background:#74C99B!important}.cq-quiz-bad{background:#EE7C8C!important}";document.head.appendChild(s);}
  function openQuiz(name){var qs=BANK[name];if(!qs)return;var i=0,score=0;var o=document.createElement("div");o.className="cq-quiz-overlay";o.innerHTML='<div class="cq-quiz-box"><h2>'+name+' Quiz</h2><p id="cqQuizQuestion"></p><div class="cq-quiz-choices" id="cqQuizChoices"></div><button class="cq-quiz-close" type="button">Close</button></div>';document.body.appendChild(o);o.querySelector(".cq-quiz-close").onclick=function(){speechSynthesis&&speechSynthesis.cancel();o.remove();};function next(){if(i>=qs.length){o.querySelector("#cqQuizQuestion").textContent="Quiz Champion! You got "+score+" out of "+qs.length+" right!";o.querySelector("#cqQuizChoices").innerHTML='<button class="cq-quiz-choice cq-quiz-good" type="button">Play again</button>';o.querySelector("#cqQuizChoices button").onclick=function(){i=0;score=0;next();};speak("Quiz Champion! You got "+score+" out of "+qs.length+" right!");return;}var q=qs[i],p=o.querySelector("#cqQuizQuestion"),c=o.querySelector("#cqQuizChoices");p.textContent=q[0];c.innerHTML="";q[1].forEach(function(label,idx){var b=document.createElement("button");b.type="button";b.className="cq-quiz-choice";b.textContent=label;b.onclick=function(){if(idx===q[2]){score++;b.classList.add("cq-quiz-good");speak("Yes! "+label+".");setTimeout(function(){i++;next();},700);}else{b.classList.add("cq-quiz-bad");speak("Try again.");setTimeout(function(){b.classList.remove("cq-quiz-bad");},500);}};c.appendChild(b);});speak(q[0]+". "+q[1].join(". "));}next();}
  function sync(){ensureStyle();var grid=document.getElementById("grid");if(!grid||!grid.classList.contains("on"))return;var cards=grid.querySelector(".cards");if(!cards)return;var name=animalName();if(!BANK[name])return;var old=cards.querySelector(".quiz-tile");if(old){old.classList.remove("locked");old.setAttribute("aria-label","Quiz: always available");}var custom=cards.querySelector(".cq-all-quiz");if(name==="Badgers"&&old){if(custom)custom.remove();return;}if(!custom){custom=document.createElement("button");custom.type="button";custom.className="card cq-all-quiz";custom.innerHTML='<span class="cq-q-art" aria-hidden="true">?</span><span class="cq-q-meta"><b>Quiz</b><small>Play the '+name+' quiz</small></span>';custom.onclick=function(){openQuiz(animalName());};cards.appendChild(custom);}var game=cards.querySelector(".cq-published-game");if(game&&game.previousElementSibling!==custom)cards.insertBefore(custom,game);}
  var queued=false;function queue(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;sync();});}
  new MutationObserver(queue).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});window.addEventListener("pageshow",queue);queue();
})();