/* Offline cache for Cub Quest.
   Bump CACHE when the site changes, so iPads pick up the new version. */
const CACHE = "cub-quest-v12";
const ASSETS = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "louis.webp",
  "icon-180.png",
  "icon-192.png",
  "icon-512.png",
  "fonts/grandstander.woff2",
  "fonts/nunito.woff2",
  "audio/hello.mp3",
  "audio/stripes.mp3",
  "audio/night.mp3",
  "audio/sett.mp3",
  "audio/dig.mp3",
  "audio/worms.mp3",
  "audio/berries.mp3",
  "audio/cubs.mp3",
  "audio/family.mp3",
  "audio/tidy.mp3",
  "audio/nose.mp3",
  "audio/sounds.mp3",
  "audio/qz_badger_which.mp3",
  "audio/qz_badger_home.mp3",
  "audio/qz_badger_daynight.mp3",
  "audio/qz_badger_eat.mp3",
  "audio/qz_badger_math1.mp3",
  "audio/qz_badger_math2.mp3",
  "audio/qz_badger_math3.mp3",
  "audio/qz_badger_done.mp3",
  "audio/party_badger.mp3",
  "audio/party_fox.mp3",
  "audio/party_bat.mp3",
  "audio/fox_hello.mp3",
  "audio/madra.mp3",
  "audio/brush.mp3",
  "audio/earth.mp3",
  "audio/ears.mp3",
  "audio/pounce.mp3",
  "audio/eyes.mp3",
  "audio/whiskers.mp3",
  "audio/foxeats.mp3",
  "audio/bury.mp3",
  "audio/foxcubs.mp3",
  "audio/foxnoises.mp3",
  "audio/bat_hello.mp3",
  "audio/bat_fly.mp3",
  "audio/bat_hands.mp3",
  "audio/bat_ears.mp3",
  "audio/bat_see.mp3",
  "audio/bat_tiny.mp3",
  "audio/bat_eat.mp3",
  "audio/bat_upside.mp3",
  "audio/bat_bigears.mp3",
  "audio/bat_roost.mp3",
  "audio/bat_winter.mp3",
  "audio/bat_pups.mp3",
  "audio/party_hedgehog.mp3",
  "audio/party_owl.mp3",
  "audio/party_otter.mp3",
  "audio/hh_hello.mp3",
  "audio/hh_spines.mp3",
  "audio/hh_ball.mp3",
  "audio/hh_legs.mp3",
  "audio/hh_eats.mp3",
  "audio/hh_winter.mp3",
  "audio/hh_nest.mp3",
  "audio/hh_hoglets.mp3",
  "audio/hh_anoint.mp3",
  "audio/hh_noise.mp3",
  "audio/hh_myth.mp3",
  "audio/hh_help.mp3",
  "audio/bo_hello.mp3",
  "audio/bo_silent.mp3",
  "audio/bo_why.mp3",
  "audio/bo_face.mp3",
  "audio/bo_ears.mp3",
  "audio/bo_dark.mp3",
  "audio/bo_pellets.mp3",
  "audio/bo_food.mp3",
  "audio/bo_screech.mp3",
  "audio/bo_eggs.mp3",
  "audio/bo_owlets.mp3",
  "audio/bo_rain.mp3",
  "audio/ot_hello.mp3",
  "audio/ot_fur.mp3",
  "audio/ot_shut.mp3",
  "audio/ot_whisk.mp3",
  "audio/ot_eyes.mp3",
  "audio/ot_dive.mp3",
  "audio/ot_fish.mp3",
  "audio/ot_holt.mp3",
  "audio/ot_cubs.mp3",
  "audio/ot_swim.mp3",
  "audio/ot_spraint.mp3",
  "audio/ot_prints.mp3",
  "audio/party_marten.mp3",
  "audio/pm_hello.mp3",
  "audio/pm_cat.mp3",
  "audio/pm_bib.mp3",
  "audio/pm_climb.mp3",
  "audio/pm_squeeze.mp3",
  "audio/pm_den.mp3",
  "audio/pm_berries.mp3",
  "audio/pm_poo.mp3",
  "audio/pm_squirrels.mp3",
  "audio/pm_kits.mp3",
  "audio/pm_rare.mp3",
  "audio/pm_noise.mp3",
  "audio/party_stoat.mp3",
  "audio/party_frog.mp3",
  "audio/party_moth.mp3",
  "audio/st_hello.mp3",
  "audio/st_easog.mp3",
  "audio/st_weasel.mp3",
  "audio/st_tail.mp3",
  "audio/st_thin.mp3",
  "audio/st_big.mp3",
  "audio/st_white.mp3",
  "audio/st_den.mp3",
  "audio/st_awake.mp3",
  "audio/st_kits.mp3",
  "audio/st_wait.mp3",
  "audio/st_old.mp3",
  "audio/fr_hello.mp3",
  "audio/fr_loscan.mp3",
  "audio/fr_spawn.mp3",
  "audio/fr_tadpole.mp3",
  "audio/fr_legs.mp3",
  "audio/fr_froglet.mp3",
  "audio/fr_skin.mp3",
  "audio/fr_winter.mp3",
  "audio/fr_colour.mp3",
  "audio/fr_tongue.mp3",
  "audio/fr_croak.mp3",
  "audio/fr_lots.mp3",
  "audio/mo_hello.mp3",
  "audio/mo_vs.mp3",
  "audio/mo_day.mp3",
  "audio/mo_tongue.mp3",
  "audio/mo_life.mp3",
  "audio/mo_cocoon.mp3",
  "audio/mo_light.mp3",
  "audio/mo_bats.mp3",
  "audio/mo_pollen.mp3",
  "audio/mo_elephant.mp3",
  "audio/mo_emperor.mp3",
  "audio/mo_clothes.mp3",
  "audio/party_seal.mp3",
  "audio/party_puffin.mp3",
  "audio/party_dolphin.mp3",
  "audio/party_shark.mp3",
  "audio/sl_hello.mp3",
  "audio/sl_nose.mp3",
  "audio/sl_pup.mp3",
  "audio/sl_milk.mp3",
  "audio/sl_dive.mp3",
  "audio/sl_whiskers.mp3",
  "audio/sl_sleep.mp3",
  "audio/sl_sing.mp3",
  "audio/sl_eat.mp3",
  "audio/sl_where.mp3",
  "audio/sl_found.mp3",
  "audio/sl_big.mp3",
  "audio/pf_hello.mp3",
  "audio/pf_beak.mp3",
  "audio/pf_fish.mp3",
  "audio/pf_fly.mp3",
  "audio/pf_swim.mp3",
  "audio/pf_burrow.mp3",
  "audio/pf_egg.mp3",
  "audio/pf_puffling.mp3",
  "audio/pf_sea.mp3",
  "audio/pf_pair.mp3",
  "audio/pf_monk.mp3",
  "audio/pf_trouble.mp3",
  "audio/dl_hello.mp3",
  "audio/dl_shannon.mp3",
  "audio/dl_click.mp3",
  "audio/dl_sleep.mp3",
  "audio/dl_breathe.mp3",
  "audio/dl_name.mp3",
  "audio/dl_fast.mp3",
  "audio/dl_calf.mp3",
  "audio/dl_porpoise.mp3",
  "audio/dl_sanctuary.mp3",
  "audio/dl_fungie.mp3",
  "audio/dl_many.mp3",
  "audio/bs_hello.mp3",
  "audio/bs_harmless.mp3",
  "audio/bs_mouth.mp3",
  "audio/bs_filter.mp3",
  "audio/bs_teeth.mp3",
  "audio/bs_name.mp3",
  "audio/bs_ireland.mp3",
  "audio/bs_many.mp3",
  "audio/bs_deep.mp3",
  "audio/bs_jump.mp3",
  "audio/bs_warm.mp3",
  "audio/bs_safe.mp3"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Cache first: once it is stored, the network is never needed again. */
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).then((res) => {
        if (res && res.ok && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      }).catch(() => caches.match("index.html"));
    })
  );
});
